repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: "v1.62.3"
  hooks:
    - id: terraform_fmt
      args:
        - --args=-no-color
        - --args=-diff
        - ./terraform
    - id: terraform_tflint
      args:
        - --args=--init
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        - --args=--enable-rule=terraform_comment_syntax
        - --args=--enable-rule=terraform_deprecated_index
        - --args=--enable-rule=terraform_deprecated_interpolation
        - --args=--enable-rule=terraform_documented_outputs
        - --args=--enable-rule=terraform_documented_variables
        - --args=--enable-rule=terraform_module_pinned_source
        - --args=--enable-rule=terraform_module_version
        - --args=--enable-rule=terraform_naming_convention
        - --args=--enable-rule=terraform_required_providers
        # - --args=--enable-rule=terraform_required_version
        # - --args=--enable-rule=terraform_standard_module_structure
        - --args=--enable-rule=terraform_typed_variables
        - --args=--enable-rule=terraform_unused_declarations
        - --args=--enable-rule=terraform_unused_required_providers
        # - --args=--enable-rule=terraform_workspace_remote
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=true
