regions:
  - eu-central-1
  - us-east-1

account-blocklist:
  - '999999999999'

accounts:
  AWS_ACCOUNT_ID_REPLACE_ME:
    presets:
      - "ignore-defaults"

feature-flags:
  disable-deletion-protection:
    RDSInstance: true
    EC2Instance: true
    CloudformationStack: true
  force-delete-lightsail-addons: true

resource-types:
  excludes:
      - AthenaWorkGroup
      - AppStreamImage
      - CloudWatchAlarm
      - CloudWatchLogsLogGroup
      - EC2DefaultSecurityGroupRule
      - ElasticacheCacheParameterGroup
      - FMSNotificationChannel
      - FMSPolicy
      - KMSAlias
      - MachineLearningBranchPrediction
      - MachineLearningDataSource
      - MachineLearningEvaluation
      - MachineLearningMLModel
      - OpsWorksUserProfile
      - RDSDBParameterGroup
      - Route53ResolverRule
      - SESReceiptFilter
      - SESReceiptRuleSet
      - SNSSubscription
      - SNSTopic

presets:
  ignore-defaults:
    filters:
      AthenaWorkGroup:
        - "primary"
      IAMUser:
        - "admin"
        - "githubactions-bot"
      MediaConvertQueue:
        - "Default"
      EC2DHCPOption:
        - property: DefaultVPC
          value: "true"
          invert: false
      EC2InternetGateway:
        - property: DefaultVPC
          value: "true"
          invert: false
      EC2InternetGatewayAttachment:
        - property: DefaultVPC
          value: "true"
          invert: false
      EC2NetworkACL:
        - "acl-945f67e9"
        - "acl-05a7e96f"
      EC2RouteTable:
        - property: DefaultVPC
          value: "true"
          invert: false
      EC2Subnet:
        - property: DefaultVPC
          value: "true"
          invert: false
      EC2SecurityGroup:
        - "sg-b86139c4"
      EC2VPC:
        - property: IsDefault
          value: "true"
          invert: false
      RDSOptionGroup:
        - property: Name
          value: "default:postgres-12"
          invert: false
      RDSDBSubnetGroup:
        - property: Name
          type: glob
          value: "default-*"
          invert: false
