---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mairror-cluster
  region: eu-central-1
  version: "1.21"
  tags:
    project: "mairror"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: external-dns
      namespace: external-dns
    wellKnownPolicies:
      externalDNS: true
  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true

nodeGroups:
  - name: ng-mairror-1
    amiFamily: AmazonLinux2
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    instanceType: t2.micro
    volumeSize: 10
    volumeType: gp3
    privateNetworking: true
    availabilityZones: ["eu-central-1"]
    containerRuntime: containerd