---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mairror-cluster
  region: eu-central-1
  version: "1.21"
  tags:
    project: "mairror"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: external-dns
      namespace: external-dns
    wellKnownPolicies:
      externalDNS: true
  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true
  - metadata:
      name: mairror-processor
      namespace: mairror
    attachPolicy: 
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "sqs:DeleteMesssage*"
        - "sqs:Get*"
        - "sqs:List*"
        - "sqs:ReceiveMessage*"
        Resource: 'arn:aws:sqs:eu-central-1:*:mairror-raw'
      - Effect: Allow
        Action:
        - "sqs:Get*"
        - "sqs:List*"
        - "sqs:Send*"
        Resource: 'arn:aws:sqs:eu-central-1:*:mairror-predict'
      - Effect: Allow
        Action:
        - "s3:ListBucket"
        Resource: 'arn:aws:s3:::mairror-images'
      - Effect: Allow
        Action:
        - "s3:GetObject"
        - "s3:GetObjectVersion"
        Resource: 'arn:aws:s3:::mairror-images/*'
  - metadata:
      name: mairror-predictor
      namespace: mairror
    attachPolicy: 
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "sqs:DeleteMesssage*"
        - "sqs:Get*"
        - "sqs:List*"
        - "sqs:ReceiveMessage*"
        Resource: 'arn:aws:sqs:eu-central-1:*:mairror-predict'
  - metadata:
      name: mairror-api
      namespace: mairror
    attachPolicy: 
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "s3:ListBucket"
        Resource: 'arn:aws:s3:::mairror-images'
      - Effect: Allow
        Action:
        - "s3:GetObject"
        - "s3:GetObjectVersion"
        - "s3:PutObject"
        Resource: 'arn:aws:s3:::mairror-images/*'

nodeGroups:
  - name: ng-mairror-1
    amiFamily: AmazonLinux2
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    instanceType: t2.micro
    volumeSize: 10
    volumeType: gp3
    privateNetworking: true
    availabilityZones: ["eu-central-1"]
    containerRuntime: containerd

