---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mairror-cluster
  region: eu-central-1
  version: "1.21"
  tags:
    project: "mairror"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: external-dns
      namespace: external-dns
    wellKnownPolicies:
      externalDNS: true
  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true

nodeGroups:
  - name: ng-mairror-1
    amiFamily: AmazonLinux2
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    instanceType: t2.micro
    volumeSize: 10
    volumeType: gp3
    privateNetworking: true
    availabilityZones: ["eu-central-1"]
    containerRuntime: containerdvpc:
  id: vpc-083795f286942da81
  subnets:
    private:
      eu-central-1a:
        id: subnet-06800f481b7b5d559
      eu-central-1b:
        id: subnet-0505257b9adc2a31b
    public:
      eu-central-1a:
        id: subnet-0f899f4c9e74d7052
      eu-central-1b:
        id: subnet-09a182f1cff4d4e96
