repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: aws-ebs-csi-driver
    url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver

helmDefaults:
  createNamespace: true

helmfiles:
  - ./*/helmfile.yaml
